version: '3'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_PORT=3000
        - REACT_APP_API=http://localhost:4000
    environment:
        CHOKIDAR_USEPOLLING: "true"
    container_name: order-creator-frontend
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: npm run start
    volumes:
      - ./frontend/src:/usr/src/app/src
    depends_on:
      - api
    networks:
      - order-creator-network

  api:
    build: ./api
    container_name: order-creator-api
    command: npm run start
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - ./api/src:/usr/src/app/src
    environment:
      - PORT=4000
      - CHOKIDAR_USEPOLLING=true
    networks:
      - order-creator-network

networks:
  order-creator-network:
    driver: bridge