version: '3'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_PORT=3000
    environment:
        CHOKIDAR_USEPOLLING: "true"
    container_name: order-creator-frontend
    ports:
      - "3001:3000"
    restart: unless-stopped
    command: npm run start
    volumes:
      - ./frontend/src:/usr/src/app/src
    networks:
      - order-creator-network

networks:
  order-creator-network:
    driver: bridge